version: '2'

services:
    lb:
      build: ./haproxy
      image: ibacalu/haproxy:2.2
      container_name: haproxy
      depends_on:
        - elastic1
        - elastic2
        - elastic3
      ports:
        - "8280:8280"
        - "9200:9200"
      networks:
        - esnet

    elastic1:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
      container_name: elastic1
      environment:
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - "discovery.zen.minimum_master_nodes=2"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      mem_limit: 1g
      volumes:
        - esdata1:/usr/share/elasticsearch/data
      ports:
        - "9201:9200"
      networks:
        - esnet

    elastic2:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
      container_name: elastic2
      depends_on:
        - elastic1
      environment:
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - "discovery.zen.ping.unicast.hosts=elastic1"
        - "discovery.zen.minimum_master_nodes=2"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      mem_limit: 1g
      volumes:
        - esdata2:/usr/share/elasticsearch/data
      ports:
        - "9202:9200"
      networks:
        - esnet

    elastic3:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
      container_name: elastic3
      depends_on:
        - elastic1
      environment:
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - "discovery.zen.ping.unicast.hosts=elastic1"
        - "discovery.zen.minimum_master_nodes=2"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      mem_limit: 1g
      volumes:
        - esdata3:/usr/share/elasticsearch/data
      ports:
        - "9203:9200"
      networks:
        - esnet
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local

networks:
  esnet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.10.0/24